openapi: 3.2.0
info:
  title: Open API
  description: Agorapulse's Open API documentation
  version: '1.0'
security:
- bearerAuth: []
tags:
- name: Open API
paths: {}
webhooks:
  PUBLISHING_POST:
    post:
      requestBody:
        description: Events related to the publishing of a post
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublishingPostEvent'
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
        '410':
          description: Return a 410 status to indicate that the endpoint is no longer active, it will automatically disable the subscription
      tags:
      - Open API
  INBOX_ITEM:
    post:
      requestBody:
        description: Events related to the life cycle of inbox items
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InboxItemEvent'
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
        '410':
          description: Return a 410 status to indicate that the endpoint is no longer active, it will automatically disable the subscription
      tags:
      - Open API
components:
  schemas:
    InboxItemEvent:
      type: object
      properties:
        uid:
          type: string
          description: Unique identifier for the event
        type:
          $ref: '#/components/schemas/InboxItemEventType'
          description: The event type
        action:
          $ref: '#/components/schemas/InboxItemAction'
          description: The action
        organizationId:
          type: integer
          format: int64
          description: Unique identifier for the organization
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the event
        payload:
          $ref: '#/components/schemas/InboxItem'
          description: The payload containing the inbox item information
    InboxItemAction:
      type: string
      enum:
      - CREATED
      - CLASSIFIED
      - LABELIZED
    PublishingPostEvent:
      type: object
      properties:
        uid:
          type: string
          description: Unique identifier for the event
        type:
          $ref: '#/components/schemas/PublishingPostEventType'
          description: The event type
        action:
          $ref: '#/components/schemas/PostAction'
          description: The action
        organizationId:
          type: integer
          format: int64
          description: Unique identifier for the organization
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the event
        payload:
          $ref: '#/components/schemas/PublishingPost'
          description: The payload containing the post information
    InboxItemCreator:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the user on social network
        name:
          type: string
          description: Name of the user
    PostStatus1:
      type: string
      enum:
      - PUBLISHED
      - FAILED
    InboxItemSentiment:
      type: string
      enum:
      - POSITIVE
      - NEGATIVE
      - NEUTRAL
    InboxItemEventType:
      type: string
      enum:
      - INBOX_ITEM
    InboxItem:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the inbox item
        parentId:
          type: string
          description: Identifier of the parent item if applicable
        workspaceId:
          type: integer
          format: int64
          description: Unique identifier for the workspace
        profile:
          $ref: '#/components/schemas/Profile1'
          description: The social network profile associated with the item
        agorapulseLink:
          type: string
          description: Link to the inbox item in Agorapulse application
        networkLink:
          type: string
          description: Link to the inbox item in the social network
        text:
          type: string
          description: Text content of the inbox item
        creationDate:
          type: string
          format: date-time
          description: Creation date of the inbox item
        type:
          $ref: '#/components/schemas/InboxItemType'
          description: Type of the inbox item
        creator:
          $ref: '#/components/schemas/InboxItemCreator'
          description: The user who created the inbox item
        labels:
          type: array
          items: string
          description: Labels associated with the item
        addedLabels:
          type: array
          items: string
          description: Labels added to the item during this event
        sentiment:
          $ref: '#/components/schemas/InboxItemSentiment'
          description: Sentiment of the inbox item
    User:
      type: object
      properties:
        uid:
          type: string
          description: Unique identifier for the user
        name:
          type: string
          description: Name of the user
        email:
          type: string
          format: email
          description: Email address of the user
    PostAction:
      type: string
      enum:
      - PUBLISHED
      - FAILED
    InboxItemType:
      type: string
      enum:
      - PRIVATE_MESSAGE
      - CONVERSATION
      - COMMENT
      - POST
    Network:
      type: string
      enum:
      - BLUESKY
      - FACEBOOK
      - GOOGLE
      - INSTAGRAM
      - LINKEDIN
      - PINTEREST
      - THREADS
      - TIKTOK
      - TWITTER
      - YOUTUBE
    PublishingPostEventType:
      type: string
      enum:
      - PUBLISHING_POST
    PublishingPost:
      type: object
      properties:
        actor:
          $ref: '#/components/schemas/User'
          description: The user who performed the action
        post:
          $ref: '#/components/schemas/Post'
          description: The post information
    Profile1:
      type: object
      properties:
        uid:
          type: string
          description: Unique identifier for the profile
        name:
          type: string
          description: Name of the profile
        network:
          $ref: '#/components/schemas/Network'
          description: The social network of the profile
    Post:
      type: object
      properties:
        uid:
          type: string
          description: Unique identifier for the post
        agorapulseLink:
          type: string
          description: Link to the post in Agorapulse application
        networkLink:
          type: string
          description: Link to the post in the social network
        publishDate:
          type: string
          format: date-time
          description: Publish date of the post
        groupUid:
          type: string
          description: Unique identifier for the group of posts if applicable
        profile:
          $ref: '#/components/schemas/Profile1'
          description: The social network profile associated with the post
        status:
          $ref: '#/components/schemas/PostStatus1'
          description: Status of the post
  securitySchemes:
    bearerAuth:
      type: apiKey
      name: X-API-KEY
      in: header
