openapi: 3.2.0
info:
  title: Open Workspace API
  description: Agorapulse's Open API documentation
  version: '1.0'
security:
- bearerAuth: []
tags:
- name: Workspace
paths:
  /v1.0/core/organizations/{organizationId}/workspaces:
    get:
      tags:
      - Workspace
      summary: Get organization workspaces
      description: List all the workspaces in an organization
      operationId: getOrganizationWorkspaces
      parameters:
      - name: organizationId
        in: path
        description: Organization id
        required: true
        schema:
          type: string
      - name: v
        in: query
        description: API version
        schema:
          type: string
      responses:
        '200':
          description: List of all workspaces in the organization
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceListResponse'
components:
  schemas:
    WorkspaceResponse_1:
      required:
      - organizationId
      - workspaceId
      - workspaceName
      type: object
      properties:
        workspaceId:
          type: integer
          format: int64
        workspaceName:
          type: string
        organizationId:
          type: integer
          format: int64
      description: Single workspace
    WorkspaceListResponse:
      required:
      - workspaces
      type: object
      properties:
        workspaces:
          type: array
          items:
            $ref: '#/components/schemas/WorkspaceResponse_1'
      description: List of workspaces
  securitySchemes:
    bearerAuth:
      type: apiKey
      name: X-API-KEY
      in: header
