openapi: 3.1.0
info:
  title: Open Calendar Notes Organization API
  description: Agorapulse's Open API documentation
  version: '1.0'
security:
- bearerAuth: []
tags:
- name: Organization
paths:
  /v1.0/core/organizations:
    get:
      tags:
      - Organization
      summary: Get manager organizations
      description: List all organizations the manager belongs to
      operationId: getManagerOrganizations
      parameters:
      - name: v
        in: query
        description: API version
        schema:
          type: string
      responses:
        '200':
          description: List of the manager organizations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationListResponse'
components:
  schemas:
    OrganizationListResponse:
      required:
      - organizations
      type: object
      properties:
        organizations:
          type: array
          items:
            $ref: '#/components/schemas/OrganizationResponse'
      description: List of organizations
    OrganizationResponse:
      required:
      - managerOrganizationRole
      - organizationId
      - organizationName
      type: object
      properties:
        organizationId:
          type: integer
          format: int64
        organizationName:
          type: string
        managerOrganizationRole:
          type: string
          deprecated: true
      description: Single organization
  securitySchemes:
    bearerAuth:
      type: apiKey
      name: X-API-KEY
      in: header
